### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by jeanmsantos** [hashicorp/boundary-ui#1708]
**Describe the bug**
After building the ui\desktop and running the application, the translations are missing.

**To Reproduce**
1. yarn install
2. yarn build:ui:desktop
3. run (...)\ui\desktop\electron-app\out\Boundary-win32-x64\Boundary.exe

**Expected behavior**
Normal application load.

**Additional context**
![image](https://github.com/hashicorp/boundary-ui/assets/30672371/9baa313d-a186-4c48-b135-17634a623379)

**Comment by randallmorey** [comment]
Hi there.  Thanks for trying Boundary Desktop.  We're aware of a problem with UI asset builds in Windows.  To work around this issue, the assets must first be built on a different platform such as Linux.  Once the UI assets are built, they may be copied to `ui/desktop/dist` and `ui/desktop/electron-app/ember-dist`.  Then run `yarn build:desktop` from `ui/desktop` on Windows.

Alternatively, you may [download the latest official release of Boundary Desktop](https://developer.hashicorp.com/boundary/downloads) for Windows.

**Comment by jeanmsantos** [comment]
Hi @randallmorey, thank you for your answer.
I tried what you suggested and it didn't work. Could you please elaborate on the workaround step-by-step process?

**Comment by calcaide** [comment]
Hi @jeanmsantos , thank you for following up.

This is a known issue for Windows environment that we are working on.

The workaround will require you to build the assets with Linux (we recommend Ubuntu) or macOS environment and copy the built assets to the Windows environment in order to proceed with the Desktop client build.

The step-by-step process is as follows:

IMPORTANT: This process assumes you are within the desktop directory `boundary-ui/ui/desktop`.

**In a Linux or MacOs environment:**
- Build the assets: `$ yarn build:production`.
- Copy the `/dist` folder from`boundary-ui/ui/desktop`.

**In the Windows environment:**
- Paste the previously copied `/dist` folder to `boundary-ui\ui\desktop`.
- Build the desktop client: `$ yarn build:desktop`.

The Boundary.exe desktop client generated within `boundary-ui\ui\desktop\electron-app\out\Boundary-win32-x64\` should include the missing translations.

Let us know if the workaround worked for you.
